[package]
name = "eapa"
version = "0.1.0"
authors = ["Maxim Molchanov <m.molchanov@vonmo.com>"]
license = "MIT/GPL"
edition = "2018"

[lib]
name = "eapa"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.4.0"
rustler = "0.21.0"
rug = "1.6.0"